### ISSUE TITLE
examples point to non-existing urls

### ISSUE THREAD

**Issue by ousia** [swf2js/swf2js#58]
@ienaga,

I’m afraid that all links from https://github.com/swf2js/swf2js#examples point to 404 targets.

**Comment by ienaga** [comment]
thank you.

**Comment by ousia** [comment]
Sorry, I closed the issue because I assumed the links were fixed.

Reopening the issue again.

**Comment by ousia** [comment]
Sorry, @ienaga, I have just realized that you fixed the presentation urls.
