### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by ienaga** [swf2js/swf2js#7]

**Comment by demurgos** [comment]
You may be interested in this Stack Exchange answer about GPU-based path rendering: https://softwareengineering.stackexchange.com/questions/191472/why-have-hardware-accelerated-vector-graphics-not-taken-off/252600#252600

Basically, I feel that WebGL would be a nice thing to have but it is not suited currently for path-based 2D graphics such as the ones used by Flash.
